#Import Library

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [16]:
import pandas as pd
import numpy as np
import re

# ðŸ“¥ Load the data

https://www.kaggle.com/datasets/gerryzani/housing-price-in-south-tangerang-city-indonesia/data

In [5]:
home = pd.read_csv("/content/drive/MyDrive/BTJ Academy/Data/190623_rumahcom_tangsel_city_unfiltered.csv", encoding='latin-1')

In [6]:
home.head()

,nav-link href,listing-location,price,bed,bath,listing-floorarea,listing-floorarea 2
0,https://www.rumah.com/listing-properti/dijual-...,"Gading Serpong, Tangerang Selatan, Banten","6,9 M",5.0,5.0,420 mÂ²,RpÂ 20.720.721Â perÂ mÂ²
1,https://www.rumah.com/listing-properti/dijual-...,"Gading Serpong, Tangerang Selatan, Banten","4,5 M",3.0,3.0,190 mÂ²,RpÂ 12.747.875Â perÂ mÂ²
2,https://www.rumah.com/listing-properti/dijual-...,"Gading Serpong, Tangerang Selatan, Banten","3,95 M",3.0,3.0,132 mÂ²,RpÂ 30.859.375Â perÂ mÂ²
3,https://www.rumah.com/listing-properti/dijual-...,"Gading Serpong, Tangerang Selatan, Banten","3,3 M",4.0,3.0,220 mÂ²,RpÂ 18.333.333Â perÂ mÂ²
4,https://www.rumah.com/listing-properti/dijual-...,"Gading Serpong, Tangerang Selatan, Banten","3,5 M",3.0,2.0,180 mÂ²,RpÂ 27.777.778Â perÂ mÂ²

# ðŸ§± STRUCTURING

In [7]:
# Check for basic info
home.info()
home.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29420 entries, 0 to 29419
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   nav-link href        29420 non-null  object
 1   listing-location     29420 non-null  object
 2   price                29420 non-null  object
 3   bed                  29282 non-null  float64
 4   bath                 29215 non-null  float64
 5   listing-floorarea    29420 non-null  object
 6   listing-floorarea 2  29383 non-null  object
dtypes: float64(2), object(5)
memory usage: 1.6+ MB

                bed          bath
count  29282.000000  29215.000000
mean       3.754457      2.986137
std        1.356762      1.359788
min        1.000000      1.000000
25%        3.000000      2.000000
50%        4.000000      3.000000
75%        4.000000      4.000000
max       10.000000     10.000000

In [8]:
# Check for missing value
home.isnull().sum()

nav-link href            0
listing-location         0
price                    0
bed                    138
bath                   205
listing-floorarea        0
listing-floorarea 2     37
dtype: int64

Di data tidak terdapat duplikat, tetapi ada missing value.

## ðŸ”„ Rename column and choose column data needed

In [9]:
home.columns

Index(['nav-link href', 'listing-location', 'price', 'bed', 'bath',
       'listing-floorarea', 'listing-floorarea 2'],
      dtype='object')

In [117]:
cols = ['listing-location', 'price', 'bed', 'bath',
       'listing-floorarea', 'listing-floorarea 2']
home2 = home[cols]
home2

,listing-location,price,bed,bath,listing-floorarea,listing-floorarea 2
0,"Gading Serpong, Tangerang Selatan, Banten","6,9 M",5.00,5.00,420 mÂ²,RpÂ 20.720.721Â perÂ mÂ²
1,"Gading Serpong, Tangerang Selatan, Banten","4,5 M",3.00,3.00,190 mÂ²,RpÂ 12.747.875Â perÂ mÂ²
2,"Gading Serpong, Tangerang Selatan, Banten","3,95 M",3.00,3.00,132 mÂ²,RpÂ 30.859.375Â perÂ mÂ²
3,"Gading Serpong, Tangerang Selatan, Banten","3,3 M",4.00,3.00,220 mÂ²,RpÂ 18.333.333Â perÂ mÂ²
4,"Gading Serpong, Tangerang Selatan, Banten","3,5 M",3.00,2.00,180 mÂ²,RpÂ 27.777.778Â perÂ mÂ²
...,...,...,...,...,...,...
29415,"Bintaro, Tangerang Selatan, Banten","3,3 M",3.00,3.00,300 mÂ²,RpÂ 21.710.526Â perÂ mÂ²
29416,"Bintaro, Tangerang Selatan, Banten",4 M,8.00,4.00,330 mÂ²,RpÂ 36.363.636Â perÂ mÂ²
29417,"Bintaro, Tangerang Selatan, Banten","2,2 M",3.00,2.00,160 mÂ²,RpÂ 18.333.333Â perÂ mÂ²
29418,"Bintaro, Tangerang Selatan, Banten","1,95 M",3.00,2.00,120 mÂ²,RpÂ 21.666.667Â perÂ mÂ²
29419,"Bintaro, Tangerang Selatan, Banten","5,5 M",4.00,3.00,200 mÂ²,RpÂ 30.555.556Â perÂ mÂ²

In [12]:
home2.columns

Index(['listing-location', 'price', 'bed', 'bath', 'listing-floorarea',
       'listing-floorarea 2'],
      dtype='object')

In [118]:
home2 = home2.rename(columns={
       'listing-location' : 'listing_location', 'listing-floorarea' : 'house_area', 'listing-floorarea 2' : 'price_area'
})
home2

,listing_location,price,bed,bath,house_area,price_area
0,"Gading Serpong, Tangerang Selatan, Banten","6,9 M",5.00,5.00,420 mÂ²,RpÂ 20.720.721Â perÂ mÂ²
1,"Gading Serpong, Tangerang Selatan, Banten","4,5 M",3.00,3.00,190 mÂ²,RpÂ 12.747.875Â perÂ mÂ²
2,"Gading Serpong, Tangerang Selatan, Banten","3,95 M",3.00,3.00,132 mÂ²,RpÂ 30.859.375Â perÂ mÂ²
3,"Gading Serpong, Tangerang Selatan, Banten","3,3 M",4.00,3.00,220 mÂ²,RpÂ 18.333.333Â perÂ mÂ²
4,"Gading Serpong, Tangerang Selatan, Banten","3,5 M",3.00,2.00,180 mÂ²,RpÂ 27.777.778Â perÂ mÂ²
...,...,...,...,...,...,...
29415,"Bintaro, Tangerang Selatan, Banten","3,3 M",3.00,3.00,300 mÂ²,RpÂ 21.710.526Â perÂ mÂ²
29416,"Bintaro, Tangerang Selatan, Banten",4 M,8.00,4.00,330 mÂ²,RpÂ 36.363.636Â perÂ mÂ²
29417,"Bintaro, Tangerang Selatan, Banten","2,2 M",3.00,2.00,160 mÂ²,RpÂ 18.333.333Â perÂ mÂ²
29418,"Bintaro, Tangerang Selatan, Banten","1,95 M",3.00,2.00,120 mÂ²,RpÂ 21.666.667Â perÂ mÂ²
29419,"Bintaro, Tangerang Selatan, Banten","5,5 M",4.00,3.00,200 mÂ²,RpÂ 30.555.556Â perÂ mÂ²

## Data Formatting

Delete unecessary format in the data

In [119]:
home2['luas_rumah'] = home2['house_area'].str.replace(' ', '', regex=False)
home2

,listing_location,price,bed,bath,house_area,price_area,luas_rumah
0,"Gading Serpong, Tangerang Selatan, Banten","6,9 M",5.00,5.00,420 mÂ²,RpÂ 20.720.721Â perÂ mÂ²,420mÂ²
1,"Gading Serpong, Tangerang Selatan, Banten","4,5 M",3.00,3.00,190 mÂ²,RpÂ 12.747.875Â perÂ mÂ²,190mÂ²
2,"Gading Serpong, Tangerang Selatan, Banten","3,95 M",3.00,3.00,132 mÂ²,RpÂ 30.859.375Â perÂ mÂ²,132mÂ²
3,"Gading Serpong, Tangerang Selatan, Banten","3,3 M",4.00,3.00,220 mÂ²,RpÂ 18.333.333Â perÂ mÂ²,220mÂ²
4,"Gading Serpong, Tangerang Selatan, Banten","3,5 M",3.00,2.00,180 mÂ²,RpÂ 27.777.778Â perÂ mÂ²,180mÂ²
...,...,...,...,...,...,...,...
29415,"Bintaro, Tangerang Selatan, Banten","3,3 M",3.00,3.00,300 mÂ²,RpÂ 21.710.526Â perÂ mÂ²,300mÂ²
29416,"Bintaro, Tangerang Selatan, Banten",4 M,8.00,4.00,330 mÂ²,RpÂ 36.363.636Â perÂ mÂ²,330mÂ²
29417,"Bintaro, Tangerang Selatan, Banten","2,2 M",3.00,2.00,160 mÂ²,RpÂ 18.333.333Â perÂ mÂ²,160mÂ²
29418,"Bintaro, Tangerang Selatan, Banten","1,95 M",3.00,2.00,120 mÂ²,RpÂ 21.666.667Â perÂ mÂ²,120mÂ²
29419,"Bintaro, Tangerang Selatan, Banten","5,5 M",4.00,3.00,200 mÂ²,RpÂ 30.555.556Â perÂ mÂ²,200mÂ²

In [120]:
home2['luas_rumah'] = home2['house_area'].str.extract(r'(.*?)(?=m)', expand=False).astype(float) #.str.extract(r'(\d+\.\d+)') #.apply(lambda x: ''.join(re.findall(r'\d.', x)))
home2

,listing_location,price,bed,bath,house_area,price_area,luas_rumah
0,"Gading Serpong, Tangerang Selatan, Banten","6,9 M",5.00,5.00,420 mÂ²,RpÂ 20.720.721Â perÂ mÂ²,420.00
1,"Gading Serpong, Tangerang Selatan, Banten","4,5 M",3.00,3.00,190 mÂ²,RpÂ 12.747.875Â perÂ mÂ²,190.00
2,"Gading Serpong, Tangerang Selatan, Banten","3,95 M",3.00,3.00,132 mÂ²,RpÂ 30.859.375Â perÂ mÂ²,132.00
3,"Gading Serpong, Tangerang Selatan, Banten","3,3 M",4.00,3.00,220 mÂ²,RpÂ 18.333.333Â perÂ mÂ²,220.00
4,"Gading Serpong, Tangerang Selatan, Banten","3,5 M",3.00,2.00,180 mÂ²,RpÂ 27.777.778Â perÂ mÂ²,180.00
...,...,...,...,...,...,...,...
29415,"Bintaro, Tangerang Selatan, Banten","3,3 M",3.00,3.00,300 mÂ²,RpÂ 21.710.526Â perÂ mÂ²,300.00
29416,"Bintaro, Tangerang Selatan, Banten",4 M,8.00,4.00,330 mÂ²,RpÂ 36.363.636Â perÂ mÂ²,330.00
29417,"Bintaro, Tangerang Selatan, Banten","2,2 M",3.00,2.00,160 mÂ²,RpÂ 18.333.333Â perÂ mÂ²,160.00
29418,"Bintaro, Tangerang Selatan, Banten","1,95 M",3.00,2.00,120 mÂ²,RpÂ 21.666.667Â perÂ mÂ²,120.00
29419,"Bintaro, Tangerang Selatan, Banten","5,5 M",4.00,3.00,200 mÂ²,RpÂ 30.555.556Â perÂ mÂ²,200.00

In [121]:
home2['harga_per_m2'] = home2['price_area'].str.replace(r'Rp\s*|\s*per\s*mÂ²', '', regex=True)
home2

,listing_location,price,bed,bath,house_area,price_area,luas_rumah,harga_per_m2
0,"Gading Serpong, Tangerang Selatan, Banten","6,9 M",5.00,5.00,420 mÂ²,RpÂ 20.720.721Â perÂ mÂ²,420.00,20.720.721
1,"Gading Serpong, Tangerang Selatan, Banten","4,5 M",3.00,3.00,190 mÂ²,RpÂ 12.747.875Â perÂ mÂ²,190.00,12.747.875
2,"Gading Serpong, Tangerang Selatan, Banten","3,95 M",3.00,3.00,132 mÂ²,RpÂ 30.859.375Â perÂ mÂ²,132.00,30.859.375
3,"Gading Serpong, Tangerang Selatan, Banten","3,3 M",4.00,3.00,220 mÂ²,RpÂ 18.333.333Â perÂ mÂ²,220.00,18.333.333
4,"Gading Serpong, Tangerang Selatan, Banten","3,5 M",3.00,2.00,180 mÂ²,RpÂ 27.777.778Â perÂ mÂ²,180.00,27.777.778
...,...,...,...,...,...,...,...,...
29415,"Bintaro, Tangerang Selatan, Banten","3,3 M",3.00,3.00,300 mÂ²,RpÂ 21.710.526Â perÂ mÂ²,300.00,21.710.526
29416,"Bintaro, Tangerang Selatan, Banten",4 M,8.00,4.00,330 mÂ²,RpÂ 36.363.636Â perÂ mÂ²,330.00,36.363.636
29417,"Bintaro, Tangerang Selatan, Banten","2,2 M",3.00,2.00,160 mÂ²,RpÂ 18.333.333Â perÂ mÂ²,160.00,18.333.333
29418,"Bintaro, Tangerang Selatan, Banten","1,95 M",3.00,2.00,120 mÂ²,RpÂ 21.666.667Â perÂ mÂ²,120.00,21.666.667
29419,"Bintaro, Tangerang Selatan, Banten","5,5 M",4.00,3.00,200 mÂ²,RpÂ 30.555.556Â perÂ mÂ²,200.00,30.555.556

In [122]:
home2['harga_per_m2'] = home2['harga_per_m2'].str.replace('.', '', regex=False).astype(float)
home2

,listing_location,price,bed,bath,house_area,price_area,luas_rumah,harga_per_m2
0,"Gading Serpong, Tangerang Selatan, Banten","6,9 M",5.00,5.00,420 mÂ²,RpÂ 20.720.721Â perÂ mÂ²,420.00,20720721.00
1,"Gading Serpong, Tangerang Selatan, Banten","4,5 M",3.00,3.00,190 mÂ²,RpÂ 12.747.875Â perÂ mÂ²,190.00,12747875.00
2,"Gading Serpong, Tangerang Selatan, Banten","3,95 M",3.00,3.00,132 mÂ²,RpÂ 30.859.375Â perÂ mÂ²,132.00,30859375.00
3,"Gading Serpong, Tangerang Selatan, Banten","3,3 M",4.00,3.00,220 mÂ²,RpÂ 18.333.333Â perÂ mÂ²,220.00,18333333.00
4,"Gading Serpong, Tangerang Selatan, Banten","3,5 M",3.00,2.00,180 mÂ²,RpÂ 27.777.778Â perÂ mÂ²,180.00,27777778.00
...,...,...,...,...,...,...,...,...
29415,"Bintaro, Tangerang Selatan, Banten","3,3 M",3.00,3.00,300 mÂ²,RpÂ 21.710.526Â perÂ mÂ²,300.00,21710526.00
29416,"Bintaro, Tangerang Selatan, Banten",4 M,8.00,4.00,330 mÂ²,RpÂ 36.363.636Â perÂ mÂ²,330.00,36363636.00
29417,"Bintaro, Tangerang Selatan, Banten","2,2 M",3.00,2.00,160 mÂ²,RpÂ 18.333.333Â perÂ mÂ²,160.00,18333333.00
29418,"Bintaro, Tangerang Selatan, Banten","1,95 M",3.00,2.00,120 mÂ²,RpÂ 21.666.667Â perÂ mÂ²,120.00,21666667.00
29419,"Bintaro, Tangerang Selatan, Banten","5,5 M",4.00,3.00,200 mÂ²,RpÂ 30.555.556Â perÂ mÂ²,200.00,30555556.00

In [123]:
home2['satuan_harga'] = home2['price'].str.replace(r'[^A-Za-z]', '', regex=True)
home2

,listing_location,price,bed,bath,house_area,price_area,luas_rumah,harga_per_m2,satuan_harga
0,"Gading Serpong, Tangerang Selatan, Banten","6,9 M",5.00,5.00,420 mÂ²,RpÂ 20.720.721Â perÂ mÂ²,420.00,20720721.00,M
1,"Gading Serpong, Tangerang Selatan, Banten","4,5 M",3.00,3.00,190 mÂ²,RpÂ 12.747.875Â perÂ mÂ²,190.00,12747875.00,M
2,"Gading Serpong, Tangerang Selatan, Banten","3,95 M",3.00,3.00,132 mÂ²,RpÂ 30.859.375Â perÂ mÂ²,132.00,30859375.00,M
3,"Gading Serpong, Tangerang Selatan, Banten","3,3 M",4.00,3.00,220 mÂ²,RpÂ 18.333.333Â perÂ mÂ²,220.00,18333333.00,M
4,"Gading Serpong, Tangerang Selatan, Banten","3,5 M",3.00,2.00,180 mÂ²,RpÂ 27.777.778Â perÂ mÂ²,180.00,27777778.00,M
...,...,...,...,...,...,...,...,...,...
29415,"Bintaro, Tangerang Selatan, Banten","3,3 M",3.00,3.00,300 mÂ²,RpÂ 21.710.526Â perÂ mÂ²,300.00,21710526.00,M
29416,"Bintaro, Tangerang Selatan, Banten",4 M,8.00,4.00,330 mÂ²,RpÂ 36.363.636Â perÂ mÂ²,330.00,36363636.00,M
29417,"Bintaro, Tangerang Selatan, Banten","2,2 M",3.00,2.00,160 mÂ²,RpÂ 18.333.333Â perÂ mÂ²,160.00,18333333.00,M
29418,"Bintaro, Tangerang Selatan, Banten","1,95 M",3.00,2.00,120 mÂ²,RpÂ 21.666.667Â perÂ mÂ²,120.00,21666667.00,M
29419,"Bintaro, Tangerang Selatan, Banten","5,5 M",4.00,3.00,200 mÂ²,RpÂ 30.555.556Â perÂ mÂ²,200.00,30555556.00,M

In [124]:
home2['satuan_harga'].unique()

array(['M', 'jt', '', 'MRpM', 'jtRpM', 'rb'], dtype=object)

In [125]:
home2['satuan_harga'].value_counts()

satuan_harga
M        24580
jt        4725
            97
rb          14
MRpM         2
jtRpM        2
Name: count, dtype: int64

In [126]:
#ganti satuan
def kategori_harga(value):
    if "jtRpM" in value:
      return "Juta"
    elif "MRpM" in value:
      return "Milyar"
    if "M" in value:
      return "Milyar"
    elif "jt" in value:
      return "Juta"
    return "Juta"

home2['kategori_harga'] = np.vectorize(kategori_harga)(home2["satuan_harga"])
home2

,listing_location,price,bed,bath,house_area,price_area,luas_rumah,harga_per_m2,satuan_harga,kategori_harga
0,"Gading Serpong, Tangerang Selatan, Banten","6,9 M",5.00,5.00,420 mÂ²,RpÂ 20.720.721Â perÂ mÂ²,420.00,20720721.00,M,Milyar
1,"Gading Serpong, Tangerang Selatan, Banten","4,5 M",3.00,3.00,190 mÂ²,RpÂ 12.747.875Â perÂ mÂ²,190.00,12747875.00,M,Milyar
2,"Gading Serpong, Tangerang Selatan, Banten","3,95 M",3.00,3.00,132 mÂ²,RpÂ 30.859.375Â perÂ mÂ²,132.00,30859375.00,M,Milyar
3,"Gading Serpong, Tangerang Selatan, Banten","3,3 M",4.00,3.00,220 mÂ²,RpÂ 18.333.333Â perÂ mÂ²,220.00,18333333.00,M,Milyar
4,"Gading Serpong, Tangerang Selatan, Banten","3,5 M",3.00,2.00,180 mÂ²,RpÂ 27.777.778Â perÂ mÂ²,180.00,27777778.00,M,Milyar
...,...,...,...,...,...,...,...,...,...,...
29415,"Bintaro, Tangerang Selatan, Banten","3,3 M",3.00,3.00,300 mÂ²,RpÂ 21.710.526Â perÂ mÂ²,300.00,21710526.00,M,Milyar
29416,"Bintaro, Tangerang Selatan, Banten",4 M,8.00,4.00,330 mÂ²,RpÂ 36.363.636Â perÂ mÂ²,330.00,36363636.00,M,Milyar
29417,"Bintaro, Tangerang Selatan, Banten","2,2 M",3.00,2.00,160 mÂ²,RpÂ 18.333.333Â perÂ mÂ²,160.00,18333333.00,M,Milyar
29418,"Bintaro, Tangerang Selatan, Banten","1,95 M",3.00,2.00,120 mÂ²,RpÂ 21.666.667Â perÂ mÂ²,120.00,21666667.00,M,Milyar
29419,"Bintaro, Tangerang Selatan, Banten","5,5 M",4.00,3.00,200 mÂ²,RpÂ 30.555.556Â perÂ mÂ²,200.00,30555556.00,M,Milyar

In [127]:
home2['harga_bangunan'] = (
    home2['price']                       # kolom asal
      .astype(str)                    # jagaâ€‘jaga kalau ada tipe nonâ€‘string
      .str.extract(r'^\s*([0-9]+(?:[.,][0-9]+)?)', expand=False)  # ambil angka pertama
      .str.replace(',', '.', regex=False)  # ubah koma â†’ titik kalau ada
      .astype(float)                  # opsional: jadi numeric
)
home2

,listing_location,price,bed,bath,house_area,price_area,luas_rumah,harga_per_m2,satuan_harga,kategori_harga,harga_bangunan
0,"Gading Serpong, Tangerang Selatan, Banten","6,9 M",5.00,5.00,420 mÂ²,RpÂ 20.720.721Â perÂ mÂ²,420.00,20720721.00,M,Milyar,6.90
1,"Gading Serpong, Tangerang Selatan, Banten","4,5 M",3.00,3.00,190 mÂ²,RpÂ 12.747.875Â perÂ mÂ²,190.00,12747875.00,M,Milyar,4.50
2,"Gading Serpong, Tangerang Selatan, Banten","3,95 M",3.00,3.00,132 mÂ²,RpÂ 30.859.375Â perÂ mÂ²,132.00,30859375.00,M,Milyar,3.95
3,"Gading Serpong, Tangerang Selatan, Banten","3,3 M",4.00,3.00,220 mÂ²,RpÂ 18.333.333Â perÂ mÂ²,220.00,18333333.00,M,Milyar,3.30
4,"Gading Serpong, Tangerang Selatan, Banten","3,5 M",3.00,2.00,180 mÂ²,RpÂ 27.777.778Â perÂ mÂ²,180.00,27777778.00,M,Milyar,3.50
...,...,...,...,...,...,...,...,...,...,...,...
29415,"Bintaro, Tangerang Selatan, Banten","3,3 M",3.00,3.00,300 mÂ²,RpÂ 21.710.526Â perÂ mÂ²,300.00,21710526.00,M,Milyar,3.30
29416,"Bintaro, Tangerang Selatan, Banten",4 M,8.00,4.00,330 mÂ²,RpÂ 36.363.636Â perÂ mÂ²,330.00,36363636.00,M,Milyar,4.00
29417,"Bintaro, Tangerang Selatan, Banten","2,2 M",3.00,2.00,160 mÂ²,RpÂ 18.333.333Â perÂ mÂ²,160.00,18333333.00,M,Milyar,2.20
29418,"Bintaro, Tangerang Selatan, Banten","1,95 M",3.00,2.00,120 mÂ²,RpÂ 21.666.667Â perÂ mÂ²,120.00,21666667.00,M,Milyar,1.95
29419,"Bintaro, Tangerang Selatan, Banten","5,5 M",4.00,3.00,200 mÂ²,RpÂ 30.555.556Â perÂ mÂ²,200.00,30555556.00,M,Milyar,5.50

In [128]:
home2[home2['harga_bangunan'].astype(str).str.count(r'\.') > 1]

Empty DataFrame
Columns: [listing_location, price, bed, bath, house_area, price_area, luas_rumah, harga_per_m2, satuan_harga, kategori_harga, harga_bangunan]
Index: []

In [129]:
def konvert_harga(harga, kategori):
    if isinstance(harga, (float, int)):
        return harga * (1000000000 if kategori == 'Milyar' else 1000000)
    else:
        return pd.to_numeric(harga.replace('.', '.'), errors='coerce') * (1000000000 if kategori == 'Milyar' else 1000000)

home2['harga_rumah'] = home2.apply(lambda row: konvert_harga(row['harga_bangunan'], row['kategori_harga']), axis=1)
pd.set_option('display.float_format', '{:.2f}'.format)
home2

,listing_location,price,bed,bath,house_area,price_area,luas_rumah,harga_per_m2,satuan_harga,kategori_harga,harga_bangunan,harga_rumah
0,"Gading Serpong, Tangerang Selatan, Banten","6,9 M",5.00,5.00,420 mÂ²,RpÂ 20.720.721Â perÂ mÂ²,420.00,20720721.00,M,Milyar,6.90,6900000000.00
1,"Gading Serpong, Tangerang Selatan, Banten","4,5 M",3.00,3.00,190 mÂ²,RpÂ 12.747.875Â perÂ mÂ²,190.00,12747875.00,M,Milyar,4.50,4500000000.00
2,"Gading Serpong, Tangerang Selatan, Banten","3,95 M",3.00,3.00,132 mÂ²,RpÂ 30.859.375Â perÂ mÂ²,132.00,30859375.00,M,Milyar,3.95,3950000000.00
3,"Gading Serpong, Tangerang Selatan, Banten","3,3 M",4.00,3.00,220 mÂ²,RpÂ 18.333.333Â perÂ mÂ²,220.00,18333333.00,M,Milyar,3.30,3300000000.00
4,"Gading Serpong, Tangerang Selatan, Banten","3,5 M",3.00,2.00,180 mÂ²,RpÂ 27.777.778Â perÂ mÂ²,180.00,27777778.00,M,Milyar,3.50,3500000000.00
...,...,...,...,...,...,...,...,...,...,...,...,...
29415,"Bintaro, Tangerang Selatan, Banten","3,3 M",3.00,3.00,300 mÂ²,RpÂ 21.710.526Â perÂ mÂ²,300.00,21710526.00,M,Milyar,3.30,3300000000.00
29416,"Bintaro, Tangerang Selatan, Banten",4 M,8.00,4.00,330 mÂ²,RpÂ 36.363.636Â perÂ mÂ²,330.00,36363636.00,M,Milyar,4.00,4000000000.00
29417,"Bintaro, Tangerang Selatan, Banten","2,2 M",3.00,2.00,160 mÂ²,RpÂ 18.333.333Â perÂ mÂ²,160.00,18333333.00,M,Milyar,2.20,2200000000.00
29418,"Bintaro, Tangerang Selatan, Banten","1,95 M",3.00,2.00,120 mÂ²,RpÂ 21.666.667Â perÂ mÂ²,120.00,21666667.00,M,Milyar,1.95,1950000000.00
29419,"Bintaro, Tangerang Selatan, Banten","5,5 M",4.00,3.00,200 mÂ²,RpÂ 30.555.556Â perÂ mÂ²,200.00,30555556.00,M,Milyar,5.50,5500000000.00

In [130]:
home2[~home2['listing_location'].str.contains(r'Tangerang\s+Selatan',
                                                 case=False,      # abaikan kapital/kecil
                                                 na=False,        # anggap NaN sebagai 'tidak mengandung'
                                                 regex=True)]
# semua rumah ada di tangerang selatan

Empty DataFrame
Columns: [listing_location, price, bed, bath, house_area, price_area, luas_rumah, harga_per_m2, satuan_harga, kategori_harga, harga_bangunan, harga_rumah]
Index: []

In [131]:
home2['lokasi'] = home2['listing_location'].str.split(',', n=1).str[0].str.strip()
home2

,listing_location,price,bed,bath,house_area,price_area,luas_rumah,harga_per_m2,satuan_harga,kategori_harga,harga_bangunan,harga_rumah,lokasi
0,"Gading Serpong, Tangerang Selatan, Banten","6,9 M",5.00,5.00,420 mÂ²,RpÂ 20.720.721Â perÂ mÂ²,420.00,20720721.00,M,Milyar,6.90,6900000000.00,Gading Serpong
1,"Gading Serpong, Tangerang Selatan, Banten","4,5 M",3.00,3.00,190 mÂ²,RpÂ 12.747.875Â perÂ mÂ²,190.00,12747875.00,M,Milyar,4.50,4500000000.00,Gading Serpong
2,"Gading Serpong, Tangerang Selatan, Banten","3,95 M",3.00,3.00,132 mÂ²,RpÂ 30.859.375Â perÂ mÂ²,132.00,30859375.00,M,Milyar,3.95,3950000000.00,Gading Serpong
3,"Gading Serpong, Tangerang Selatan, Banten","3,3 M",4.00,3.00,220 mÂ²,RpÂ 18.333.333Â perÂ mÂ²,220.00,18333333.00,M,Milyar,3.30,3300000000.00,Gading Serpong
4,"Gading Serpong, Tangerang Selatan, Banten","3,5 M",3.00,2.00,180 mÂ²,RpÂ 27.777.778Â perÂ mÂ²,180.00,27777778.00,M,Milyar,3.50,3500000000.00,Gading Serpong
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29415,"Bintaro, Tangerang Selatan, Banten","3,3 M",3.00,3.00,300 mÂ²,RpÂ 21.710.526Â perÂ mÂ²,300.00,21710526.00,M,Milyar,3.30,3300000000.00,Bintaro
29416,"Bintaro, Tangerang Selatan, Banten",4 M,8.00,4.00,330 mÂ²,RpÂ 36.363.636Â perÂ mÂ²,330.00,36363636.00,M,Milyar,4.00,4000000000.00,Bintaro
29417,"Bintaro, Tangerang Selatan, Banten","2,2 M",3.00,2.00,160 mÂ²,RpÂ 18.333.333Â perÂ mÂ²,160.00,18333333.00,M,Milyar,2.20,2200000000.00,Bintaro
29418,"Bintaro, Tangerang Selatan, Banten","1,95 M",3.00,2.00,120 mÂ²,RpÂ 21.666.667Â perÂ mÂ²,120.00,21666667.00,M,Milyar,1.95,1950000000.00,Bintaro
29419,"Bintaro, Tangerang Selatan, Banten","5,5 M",4.00,3.00,200 mÂ²,RpÂ 30.555.556Â perÂ mÂ²,200.00,30555556.00,M,Milyar,5.50,5500000000.00,Bintaro

In [159]:
home3 = home2.drop(columns=['listing_location', 'price', 'house_area', 'price_area', 'satuan_harga', 'kategori_harga', 'harga_bangunan'])
home3

       bed  bath  luas_rumah  harga_per_m2   harga_rumah          lokasi
0     5.00  5.00      420.00   20720721.00 6900000000.00  Gading Serpong
1     3.00  3.00      190.00   12747875.00 4500000000.00  Gading Serpong
2     3.00  3.00      132.00   30859375.00 3950000000.00  Gading Serpong
3     4.00  3.00      220.00   18333333.00 3300000000.00  Gading Serpong
4     3.00  2.00      180.00   27777778.00 3500000000.00  Gading Serpong
...    ...   ...         ...           ...           ...             ...
29415 3.00  3.00      300.00   21710526.00 3300000000.00         Bintaro
29416 8.00  4.00      330.00   36363636.00 4000000000.00         Bintaro
29417 3.00  2.00      160.00   18333333.00 2200000000.00         Bintaro
29418 3.00  2.00      120.00   21666667.00 1950000000.00         Bintaro
29419 4.00  3.00      200.00   30555556.00 5500000000.00         Bintaro

[29420 rows x 6 columns]

In [134]:
home3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29420 entries, 0 to 29419
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   bed           29282 non-null  float64
 1   bath          29215 non-null  float64
 2   luas_rumah    29420 non-null  float64
 3   harga_per_m2  29383 non-null  float64
 4   harga_rumah   29420 non-null  float64
 5   lokasi        29420 non-null  object
dtypes: float64(5), object(1)
memory usage: 1.3+ MB

# ðŸ§¹ CLEANING

## ðŸ§½ Remove duplicates

In [135]:
# Check for duplicate
home3.duplicated().sum()

np.int64(9097)

Tidak ada duplikat dalam data.

In [160]:
# drop duplikat
home3 = home3.drop_duplicates()
home3.duplicated().sum()

np.int64(0)

In [137]:
home3.shape

(20323, 6)

## Handle Outliers

outlier ditangani dulu sebelum mengisi missing value karena apabila pengisian missing value menggunakan mean, maka akan terpengaruh outlier

In [138]:
home3.describe()

           bed     bath  luas_rumah   harga_per_m2     harga_rumah
count 20214.00 20163.00    20323.00       20290.00        20323.00
mean      3.78     3.02      221.64    35718758.42   3725240257.67
std       1.36     1.36     2967.93   576666387.55   7808624054.27
min       1.00     1.00        1.00           0.00      1000000.00
25%       3.00     2.00       85.00    13333333.00   1410000000.00
50%       4.00     3.00      148.00    18427242.00   2500000000.00
75%       5.00     4.00      245.00    24166667.00   4490500000.00
max      10.00    10.00   400000.00 29375000000.00 850000000000.00

In [161]:
home3[home3['luas_rumah'] < 28.28].sort_values(by='luas_rumah')

,bed,bath,luas_rumah,harga_per_m2,harga_rumah,lokasi
952,NaN,NaN,1.00,3583333.00,215000000.00,SATU-SATUNYA KAVLING SIAP BANGUN DI PAMULANG
10679,4.00,3.00,1.00,17293233.00,2300000000.00,pamulang barat
11288,NaN,NaN,1.00,14750000.00,2950000000.00,Alam Sutera
11714,3.00,3.00,1.00,14141414.00,1400000000.00,Jl.kihajar dewantara kampung sawah ciputat
26435,4.00,3.00,1.00,16509434.00,3500000000.00,Alam Sutera
24301,4.00,3.00,1.00,4900000000.00,4900000000.00,Pasadena
14295,2.00,2.00,1.00,9375000.00,1500000000.00,vila bintaro indah Tanggerang selatan
26438,2.00,1.00,1.00,12359722.00,889900000.00,Gading Serpong
28787,2.00,3.00,1.00,31250000.00,1500000000.00,Gading Serpong
25654,6.00,4.00,3.00,416666667.00,2500000000.00,Villa melati mas
13493,3.00,2.00,5.00,10.00,600000000.00,Jl. Ciputat Bsd 22
16853,NaN,NaN,10.00,11923077.00,3100000000.00,BSD
11760,2.00,1.00,10.00,100.00,1000000.00,Pamulang
10320,NaN,NaN,21.00,37500000.00,900000000.00,Bintaro Sektor 9
13863,2.00,1.00,22.00,8750000.00,525000000.00,Parung Panjang
22960,1.00,1.00,24.00,2545455.00,168000000.00,Sentra Hills Tenjo
3592,1.00,1.00,26.00,23769231.00,618000000.00,Jalur Sutera Barat
10268,2.00,2.00,26.00,5046875.00,323000000.00,Jln.Intan 1
3095,2.00,1.00,27.00,2500000.00,150000000.00,maja
3102,2.00,1.00,27.00,6283333.00,377000000.00,JL raya dago WA 081288467046
16293,2.00,1.00,27.00,5833333.00,350000000.00,Jl Pisang Raya Parung Panjang
3125,1.00,1.00,27.00,8250000.00,495000000.00,Serpong Utara
13870,2.00,1.00,27.00,2508333.00,150500000.00,Permata mutiara maja
15307,2.00,1.00,27.00,8600000.00,516000000.00,jln raya dago parung panjang
3103,2.00,1.00,27.00,3515000.00,210900000.00,jl. Jasinga Tenjo
28668,2.00,1.00,27.00,2508333.00,150500000.00,Jl. PDAM
3099,2.00,1.00,27.00,3515000.00,210900000.00,Jalan Jasinga Tenjo
10476,2.00,1.00,28.00,13400000.00,670000000.00,Jl. Raya Cisauk Lapan
3091,2.00,1.00,28.00,2800000.00,168000000.00,Jln Cibunar Parung Panjang Wa 085715056383
10479,2.00,1.00,28.00,2800000.00,168000000.00,Puri Harmoni 8 Parung Panjang
4003,2.00,1.00,28.00,15440000.00,772000000.00,MJFC+7X Cisauk
721,2.00,1.00,28.00,15440000.00,772000000.00,Cisauk
23169,2.00,1.00,28.00,13600000.00,680000000.00,Jl Cisauk
20660,2.00,1.00,28.00,12416667.00,745000000.00,jl Bellevue
14854,2.00,1.00,28.00,5105263.00,291000000.00,Jalan Bulak Saga
27104,2.00,1.00,28.00,13066667.00,784000000.00,Serpong

In [162]:
# Handle outlier luas rumah
home3.loc[(home3['luas_rumah'] < 28.8), 'luas_rumah'] = 28.8
home3.describe()

           bed     bath  luas_rumah   harga_per_m2     harga_rumah
count 20214.00 20163.00    20323.00       20290.00        20323.00
mean      3.78     3.02      221.66    35718758.42   3725240257.67
std       1.36     1.36     2967.93   576666387.55   7808624054.27
min       1.00     1.00       28.80           0.00      1000000.00
25%       3.00     2.00       85.00    13333333.00   1410000000.00
50%       4.00     3.00      148.00    18427242.00   2500000000.00
75%       5.00     4.00      245.00    24166667.00   4490500000.00
max      10.00    10.00   400000.00 29375000000.00 850000000000.00

In [163]:
home3[home3['luas_rumah'] > 245].sort_values(by='luas_rumah')

       bed  bath  luas_rumah  harga_per_m2   harga_rumah              lokasi
6188  5.00  5.00      246.00   22916667.00 5500000000.00         Alam Sutera
10940 4.00  4.00      246.00   23333333.00 5600000000.00         Alam Sutera
10665 5.00  5.00      246.00   24166667.00 5800000000.00         Alam Sutera
21889 3.00  3.00      246.00   14361702.00 6750000000.00  BINTARO SEKTRO VII
14893 4.00  4.00      246.00   44444444.00 8000000000.00           Nava Park
...    ...   ...         ...           ...           ...                 ...
6730  3.00  2.00    13000.00   10925926.00 2950000000.00         BALI  VIEW9
19381 4.00  5.00    25015.00   30000000.00 4800000000.00             Bintaro
27781 4.00  4.00    88300.00    7812500.00 2500000000.00             Ciputat
20987 3.00  2.00   100150.00   12666667.00 1900000000.00                 BSD
17321 6.00  4.00   400000.00   12000000.00 3000000000.00       Ciputat Timur

[5080 rows x 6 columns]

In [164]:
# Handle outlier temperature
home3.loc[(home3['luas_rumah'] > 245), 'luas_rumah'] = 245
home3.describe()

           bed     bath  luas_rumah   harga_per_m2     harga_rumah
count 20214.00 20163.00    20323.00       20290.00        20323.00
mean      3.78     3.02      151.44    35718758.42   3725240257.67
std       1.36     1.36       72.39   576666387.55   7808624054.27
min       1.00     1.00       28.80           0.00      1000000.00
25%       3.00     2.00       85.00    13333333.00   1410000000.00
50%       4.00     3.00      148.00    18427242.00   2500000000.00
75%       5.00     4.00      245.00    24166667.00   4490500000.00
max      10.00    10.00      245.00 29375000000.00 850000000000.00

In [165]:
home3[home3['harga_per_m2'] < 950000].sort_values(by='harga_per_m2')

,bed,bath,luas_rumah,harga_per_m2,harga_rumah,lokasi
11372,4.00,3.00,245.00,0.00,4000000.00,Jl Bintaro Jaya Sektor 9 -Taman Puri Bintaro
8887,2.00,1.00,36.00,0.00,1000000.00,Stasiun Daru
4128,4.00,3.00,165.00,1.00,148000000.00,Gading serpong
9189,5.00,5.00,170.00,1.00,300000000.00,Alam Sutera
8498,2.00,1.00,46.00,5.00,300000000.00,Serpong
...,...,...,...,...,...,...
319,2.00,2.00,50.00,833333.00,50000000.00,Jl. Hasyim Ashari
3321,4.00,4.00,245.00,833333.00,150000000.00,Jl Perkici
6090,3.00,3.00,73.00,852273.00,75000000.00,Jl.kebon kopi pengasinan gunung Sindur
20765,3.00,3.00,196.00,879121.00,80000000.00,Discovery Bintaro
219,3.00,2.00,55.00,937500.00,45000000.00,Malibu village gading serpong

In [166]:
home3.loc[home3['harga_per_m2'] < 950000, 'harga_per_m2'] = 950000

In [167]:
home3[home3['harga_per_m2'] > 75000000].sort_values(by='harga_per_m2')

,bed,bath,luas_rumah,harga_per_m2,harga_rumah,lokasi
1758,5.00,4.00,245.00,75338800.00,22601640000.00,Jl Grand Boulevard BSD City Pagedangan Tangerang
9629,5.00,5.00,245.00,75757576.00,30000000000.00,Bsd
510,8.00,6.00,245.00,76086957.00,17500000000.00,BSD
23571,3.00,3.00,72.00,83333333.00,8250000000.00,Pamulang
20098,5.00,4.00,245.00,86065574.00,10500000000.00,Jl. Raya Grand Boulevard
13445,5.00,3.00,204.00,87912088.00,16000000000.00,Jl Tulodong
18991,3.00,3.00,245.00,95445217.00,21952400000.00,BSD
13426,10.00,10.00,245.00,104166667.00,45000000000.00,BSD
6388,4.00,5.00,245.00,112288491.00,25826352941.00,Jl. Bumi Foresta
27793,2.00,2.00,60.00,124305556.00,8950000000.00,Bsd Nusaloka Serpong
243,5.00,3.00,198.00,125000000.00,33000000000.00,Bintaro
27656,4.00,3.00,245.00,157142857.00,3300000000.00,bintaro sektor 9
7069,2.00,1.00,41.00,173611111.00,12500000000.00,Bintaro
16856,5.00,4.00,160.00,186111111.00,3350000000.00,Ciputat Timur
2503,4.00,3.00,245.00,194000000.00,4850000000.00,BSD THE GREEN CLUSTER VINEYARD
18895,2.00,2.00,120.00,200000000.00,2000000000.00,Fluorite
21600,5.00,4.00,128.00,212500000.00,2550000000.00,Cluster Edison
17352,5.00,5.00,170.00,264957265.00,31000000000.00,Kucica Bintaro Sektor 9
685,4.00,3.00,130.00,325000000.00,19500000000.00,Sektor 9 Bintaro
25654,6.00,4.00,28.80,416666667.00,2500000000.00,Villa melati mas
1701,4.00,4.00,245.00,525000000.00,105000000000.00,BSD Boulevard Lengkong Kulon Pagedangan
716,5.00,4.00,245.00,562687030.00,313979363000.00,Bumi Botanika Utara Lengkong Pagedangan Tangerang
1474,4.00,3.00,210.00,1312500000.00,5250000000.00,Discovery Bintaro
10470,4.00,3.00,80.00,2250000000.00,135000000002.00,jln siliwangi pamulang tangerang selatan
24301,4.00,3.00,28.80,4900000000.00,4900000000.00,Pasadena
26111,3.00,2.00,70.00,9444444444.00,850000000000.00,pondok aren Tanggerang selatan
10023,3.00,2.00,98.00,10714285714.00,1050000000.00,BSD
15534,4.00,3.00,245.00,11705685619.00,3500000000.00,Puspita loka
10360,10.00,6.00,245.00,12135922330.00,2500000000.00,Jln. H. Sarmili
10699,3.00,2.00,150.00,13000000000.00,1300000000.00,jl boulevard raya
1739,6.00,4.00,245.00,13157894737.00,11500000000.00,Sektor dua
24206,3.00,2.00,80.00,15416666667.00,1850000000.00,Bintaro
485,4.00,2.00,144.00,16406250000.00,2100000000.00,Alam Sutera
11497,3.00,3.00,200.00,19166666667.00,3450000000.00,The Greean road
25671,4.00,3.00,245.00,19428571429.00,3400000000.00,Nusaloka
23079,3.00,2.00,90.00,21666666667.00,1300000000.00,jl. raya dago 081288469046
8957,6.00,3.00,245.00,21666666667.00,7800000000.00,Jl Boulevard Bintaro Jaya
2437,4.00,4.00,133.00,24553571429.00,2750000000.00,Hyland
423,3.00,2.00,88.00,25892857143.00,1450000000.00,BSD
20105,5.00,6.00,245.00,27070063694.00,4250000000.00,Bintaro Sektor 9
22601,4.00,3.00,193.00,29012345679.00,4700000000.00,Gading serpong
2776,3.00,3.00,170.00,29375000000.00,2350000000.00,Ciputat

In [168]:
home3.loc[home3['harga_per_m2'] > 75000000, 'harga_per_m2'] = 75000000

In [171]:
home3.describe()

           bed     bath  luas_rumah  harga_per_m2     harga_rumah
count 20214.00 20163.00    20323.00      20290.00        20323.00
mean      3.78     3.02      151.44   19491603.10   3725622506.52
std       1.36     1.36       72.39    9022280.56   7808444440.75
min       1.00     1.00       28.80     950000.00    100000000.00
25%       3.00     2.00       85.00   13333333.00   1410000000.00
50%       4.00     3.00      148.00   18427242.00   2500000000.00
75%       5.00     4.00      245.00   24166667.00   4490500000.00
max      10.00    10.00      245.00   75000000.00 850000000000.00

In [169]:
home3[home3['harga_rumah'] < 100000000].sort_values(by='harga_rumah')

,bed,bath,luas_rumah,harga_per_m2,harga_rumah,lokasi
11760,2.00,1.00,28.80,950000.00,1000000.00,Pamulang
8887,2.00,1.00,36.00,950000.00,1000000.00,Stasiun Daru
20379,3.00,2.00,80.00,950000.00,1050000.00,Jl pesantren komplek pajak
20091,3.00,2.00,61.00,950000.00,1099000.00,BSD
6308,2.00,2.00,100.00,950000.00,1100000.00,Ciputat
...,...,...,...,...,...,...
15545,4.00,4.00,190.00,950000.00,90000000.00,The Greenn Bsd
13216,3.00,2.00,55.00,1428571.00,90000000.00,Bsd
29238,6.00,4.00,200.00,950000.00,90000000.00,Pondok Aren
19024,2.00,1.00,50.00,950000.00,95000000.00,Jln.keaadaran
21142,5.00,3.00,200.00,1088889.00,98000000.00,Jl Red Diamond

In [170]:
home3.loc[home3['harga_rumah'] < 100000000, 'harga_rumah'] = 100000000

In [172]:
home3[home3['harga_rumah'] > 5000000000].sort_values(by='harga_rumah')

,bed,bath,luas_rumah,harga_per_m2,harga_rumah,lokasi
1814,4.00,4.00,217.00,27847679.00,5012582282.00,Gading Serpong Tangerang
6379,3.00,4.00,207.00,35020833.00,5043000000.00,Jl. Springs Boulevard
26056,4.00,3.00,176.00,36128571.00,5058000000.00,Alam Sutera
9686,5.00,4.00,176.00,36128571.00,5058000000.00,Sutera Narada 1
9876,4.00,6.00,227.00,26771332.00,5086553120.00,Jl. Bumi Serpong Damai
...,...,...,...,...,...,...
20216,3.00,7.00,245.00,32393910.00,100000000000.00,BSD
1701,4.00,4.00,245.00,75000000.00,105000000000.00,BSD Boulevard Lengkong Kulon Pagedangan
10470,4.00,3.00,80.00,75000000.00,135000000002.00,jln siliwangi pamulang tangerang selatan
716,5.00,4.00,245.00,75000000.00,313979363000.00,Bumi Botanika Utara Lengkong Pagedangan Tangerang
26111,3.00,2.00,70.00,75000000.00,850000000000.00,pondok aren Tanggerang selatan

In [173]:
home3.loc[home3['harga_rumah'] > 5000000000, 'harga_rumah'] = 5000000000

In [174]:
home3.describe()

           bed     bath  luas_rumah  harga_per_m2   harga_rumah
count 20214.00 20163.00    20323.00      20290.00      20323.00
mean      3.78     3.02      151.44   19491603.10 2768584449.03
std       1.36     1.36       72.39    9022280.56 1551441887.51
min       1.00     1.00       28.80     950000.00  100000000.00
25%       3.00     2.00       85.00   13333333.00 1410000000.00
50%       4.00     3.00      148.00   18427242.00 2500000000.00
75%       5.00     4.00      245.00   24166667.00 4490500000.00
max      10.00    10.00      245.00   75000000.00 5000000000.00

## Check missing values

In [175]:
home3.isnull().sum()

bed             109
bath            160
luas_rumah        0
harga_per_m2     33
harga_rumah       0
lokasi            0
dtype: int64

In [176]:
home3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20323 entries, 0 to 29419
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   bed           20214 non-null  float64
 1   bath          20163 non-null  float64
 2   luas_rumah    20323 non-null  float64
 3   harga_per_m2  20290 non-null  float64
 4   harga_rumah   20323 non-null  float64
 5   lokasi        20323 non-null  object
dtypes: float64(5), object(1)
memory usage: 1.1+ MB

In [178]:
# 1. Harga rumah â†’ mean per lokasi (round 2)
# â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
mean_per_loc = (
    home3.groupby('lokasi')['harga_per_m2']
      .transform(lambda x: round(x.mean(), 2))   # hitung mean & bulatkan 2 desimal
)

home3['harga_tiap_m2'] = home3['harga_per_m2'].fillna(mean_per_loc)

<ipython-input-178-2870170925>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  home3['harga_tiap_m2'] = home3['harga_per_m2'].fillna(mean_per_loc)

In [179]:
mean_floor_per_loc = (
    home3.groupby('lokasi')['bed']
      .transform(lambda x: np.floor(x.mean()).astype(int))
)

home3['jumlah_kamar'] = home3['bed'].fillna(mean_floor_per_loc)

<ipython-input-179-947492154>:3: RuntimeWarning: invalid value encountered in cast
  .transform(lambda x: np.floor(x.mean()).astype(int))
<ipython-input-179-947492154>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  home3['jumlah_kamar'] = home3['bed'].fillna(mean_floor_per_loc)

In [180]:
mean_floor_per_loc = (
    home3.groupby('lokasi')['bath']
      .transform(lambda x: np.floor(x.mean()).astype(int))
)

home3['jumlah_km'] = home3['bath'].fillna(mean_floor_per_loc)

<ipython-input-180-3146117303>:3: RuntimeWarning: invalid value encountered in cast
  .transform(lambda x: np.floor(x.mean()).astype(int))
<ipython-input-180-3146117303>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  home3['jumlah_km'] = home3['bath'].fillna(mean_floor_per_loc)

In [186]:
home3.isnull().sum()

bed               109
bath              160
luas_rumah          0
harga_per_m2       33
harga_rumah         0
lokasi              0
harga_bangunan      8
harga_tiap_m2       8
jumlah_kamar        0
jumlah_km           0
dtype: int64

In [188]:
home3[home3['harga_tiap_m2'].isna()]

,bed,bath,luas_rumah,harga_per_m2,harga_rumah,lokasi,harga_bangunan,harga_tiap_m2,jumlah_kamar,jumlah_km
613,4.00,3.00,140.00,NaN,2200000000.00,10 Jl. Ki Hajar Dewantara,NaN,NaN,4.00,3.00
623,2.00,2.00,69.00,NaN,1080000000.00,Jl Benosa,NaN,NaN,2.00,2.00
6837,2.00,1.00,36.00,NaN,1400000000.00,Jalan Kemiri - Pondok cabe udik,NaN,NaN,2.00,1.00
10639,3.00,2.00,68.00,NaN,1290000000.00,Jl Cendrawasi Raya Bintaro,NaN,NaN,3.00,2.00
10647,3.00,2.00,68.00,NaN,1290000000.00,Jl Cendrawasih Raya,NaN,NaN,3.00,2.00
14230,3.00,2.00,68.00,NaN,1290000000.00,Griya Bintaro Estate Jl. Raya Cendrawasih,NaN,NaN,3.00,2.00
14510,6.00,6.00,245.00,NaN,5000000000.00,BSD City Lengkong Kulon,NaN,NaN,6.00,6.00
23378,4.00,2.00,150.00,NaN,1000000000.00,Jl. Permai Bar,NaN,NaN,4.00,2.00

In [189]:
home3 = home3.dropna(subset=['harga_tiap_m2'])
home3.isnull().sum()

bed               109
bath              160
luas_rumah          0
harga_per_m2       25
harga_rumah         0
lokasi              0
harga_bangunan      0
harga_tiap_m2       0
jumlah_kamar        0
jumlah_km           0
dtype: int64

In [226]:
# Optional: drop other nulls
home4 = home3.drop(columns=['harga_per_m2','bed','bath'])
home4.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20315 entries, 0 to 29419
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   luas_rumah      20315 non-null  float64
 1   harga_rumah     20315 non-null  float64
 2   lokasi          20315 non-null  object
 3   harga_bangunan  20315 non-null  float64
 4   harga_tiap_m2   20315 non-null  float64
 5   jumlah_kamar    20315 non-null  float64
 6   jumlah_km       20315 non-null  float64
dtypes: float64(6), object(1)
memory usage: 1.2+ MB

In [192]:
home4.isnull().sum()

luas_rumah        0
harga_rumah       0
lokasi            0
harga_bangunan    0
harga_tiap_m2     0
jumlah_kamar      0
jumlah_km         0
dtype: int64

# ENRICHING

In [193]:
home4.head()

,luas_rumah,harga_rumah,lokasi,harga_bangunan,harga_tiap_m2,jumlah_kamar,jumlah_km
0,245.00,5000000000.00,Gading Serpong,20720721.00,20720721.00,5.00,5.00
1,190.00,4500000000.00,Gading Serpong,12747875.00,12747875.00,3.00,3.00
2,132.00,3950000000.00,Gading Serpong,30859375.00,30859375.00,3.00,3.00
3,220.00,3300000000.00,Gading Serpong,18333333.00,18333333.00,4.00,3.00
4,180.00,3500000000.00,Gading Serpong,27777778.00,27777778.00,3.00,2.00

In [227]:
# Menambahkan data kecamatan dan kelurahan
kecamatan_list = ['Ciputat', 'Ciputat Timur', 'Pamulang', 'Pondok Aren', 'Serpong', 'Serpong Utara', 'Setu']
kelurahan_list = kelurahan_list = [
    "Cipayung", "Ciputat", "Jombang", "Sawah Baru", "Sawah Lama", "Serua", "Serua Indah",
    "Cempaka Putih", "Cireundeu", "Pisangan", "Pondok Ranji", "Rempoa", "Rengas",
    "Bambu Apus", "Benda Baru", "Kedaung", "Pamulang Barat", "Pamulang Timur",
    "Pondok Benda", "Pondok Cabe Ilir", "Pondok Cabe Udik",
    "Jurangmangu Barat", "Jurangmangu Timur", "Pondok Kacang Barat", "Pondok Kacang Timur",
    "Perigi Lama", "Perigi Baru", "Pondok Aren", "Pondok Karya", "Pondok Jaya",
    "Pondok Betung", "Pondok Pucung",
    "Buaran", "Ciater", "Cilenggang", "Lengkong Gudang", "Lengkong Gudang Timur",
    "Lengkong Wetan", "Rawa Buntu", "Rawa Mekar Jaya", "Serpong",
    "Jelupang", "Lengkong Karya", "Pakualam", "Pakulonan", "Paku Jaya",
    "Pondok Jagung", "Pondok Jagung Timur",
    "Babakan", "Bakti Jaya", "Kademangan", "Keranggan", "Muncul", "Setu"
]

In [228]:
def extract_kecamatan(listing_location, kecamatan_list):
    for kecamatan in kecamatan_list:
        if kecamatan.lower() in listing_location.lower():
            return kecamatan
    return None

home4["Kecamatan"] = home4["lokasi"].apply(lambda x: extract_kecamatan(x, kecamatan_list))

In [229]:
def extract_kelurahan(listing_location, kelurahan_list):
    for kelurahan in kelurahan_list:
        if kelurahan.lower() in listing_location.lower():
            return kelurahan
    return None

home4["kelurahan"] = home4["lokasi"].apply(lambda x: extract_kelurahan(x, kelurahan_list))

In [211]:
home4.head()

,luas_rumah,harga_rumah,lokasi,harga_bangunan,harga_tiap_m2,jumlah_kamar,jumlah_km,Kecamatan,kelurahan
0,245.00,5000000000.00,Gading Serpong,20720721.00,20720721.00,5.00,5.00,Serpong,Serpong
1,190.00,4500000000.00,Gading Serpong,12747875.00,12747875.00,3.00,3.00,Serpong,Serpong
2,132.00,3950000000.00,Gading Serpong,30859375.00,30859375.00,3.00,3.00,Serpong,Serpong
3,220.00,3300000000.00,Gading Serpong,18333333.00,18333333.00,4.00,3.00,Serpong,Serpong
4,180.00,3500000000.00,Gading Serpong,27777778.00,27777778.00,3.00,2.00,Serpong,Serpong

# ðŸ§ª VALIDATION

In [230]:
# 1. Basic Info
print("Basic info:")
home4.info()

Basic info:
<class 'pandas.core.frame.DataFrame'>
Index: 20315 entries, 0 to 29419
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   luas_rumah      20315 non-null  float64
 1   harga_rumah     20315 non-null  float64
 2   lokasi          20315 non-null  object
 3   harga_bangunan  20315 non-null  float64
 4   harga_tiap_m2   20315 non-null  float64
 5   jumlah_kamar    20315 non-null  float64
 6   jumlah_km       20315 non-null  float64
 7   Kecamatan       4861 non-null   object
 8   kelurahan       4903 non-null   object
dtypes: float64(6), object(3)
memory usage: 1.5+ MB

In [231]:
home4['Kecamatan'] = home4['Kecamatan'].fillna('lainnya')
home4['kelurahan'] = home4['kelurahan'].fillna('lainnya')

In [220]:
home4.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20315 entries, 0 to 29419
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   luas_rumah     20315 non-null  float64
 1   harga_rumah    20315 non-null  float64
 2   lokasi         20315 non-null  object
 3   harga_tiap_m2  20315 non-null  float64
 4   jumlah_kamar   20315 non-null  float64
 5   jumlah_km      20315 non-null  float64
 6   Kecamatan      20315 non-null  object
 7   kelurahan      20315 non-null  object
dtypes: float64(5), object(3)
memory usage: 1.4+ MB

In [232]:
# 2. Check for missing values
print("Missing values:")
print(home4.isnull().sum())

Missing values:
luas_rumah        0
harga_rumah       0
lokasi            0
harga_bangunan    0
harga_tiap_m2     0
jumlah_kamar      0
jumlah_km         0
Kecamatan         0
kelurahan         0
dtype: int64

In [233]:
# 3. Range and validity checks
if 'luas_rumah' in home4.columns:
    print(f"luas_rumah range: {home4['luas_rumah'].min()} to {home4['luas_rumah'].max()}")
if 'harga_rumah' in home4.columns:
    print(f"harga_rumah range: {home4['harga_rumah'].min()} to {home4['harga_rumah'].max()}")
if 'harga_tiap_m2' in home4.columns:
    print(f"harga_tiap_m2 range: {home4['harga_tiap_m2'].min()} to {home4['harga_tiap_m2'].max()}")
if 'jumlah_kamar' in home4.columns:
    print(f"jumlah_kamar range: {home4['jumlah_kamar'].min()} to {home4['jumlah_kamar'].max()}")
if 'jumlah_km' in home4.columns:
    print(f"jumlah_km range: {home4['jumlah_km'].min()} to {home4['jumlah_km'].max()}")

luas_rumah range: 28.8 to 245.0
harga_rumah range: 100000000.0 to 5000000000.0
harga_tiap_m2 range: 950000.0 to 75000000.0
jumlah_kamar range: -9.223372036854776e+18 to 10.0
jumlah_km range: -9.223372036854776e+18 to 10.0

In [234]:
home4.loc[(home4['jumlah_kamar'] < 1), 'jumlah_kamar'] = 1
home4.loc[(home4['jumlah_km'] < 1), 'jumlah_km'] = 1

In [235]:
if 'jumlah_kamar' in home4.columns:
    print(f"jumlah_kamar range: {home4['jumlah_kamar'].min()} to {home4['jumlah_kamar'].max()}")
if 'jumlah_km' in home4.columns:
    print(f"jumlah_km range: {home4['jumlah_km'].min()} to {home4['jumlah_km'].max()}")

jumlah_kamar range: 1.0 to 10.0
jumlah_km range: 1.0 to 10.0

In [236]:
# 4. Check for duplicates
print(f"Duplicate rows in home4: {home4.duplicated().sum()}")

Duplicate rows in home4: 78

In [237]:
home4 = home4.drop_duplicates()
home4.duplicated().sum()

np.int64(0)

In [238]:
home4.to_csv('/content/drive/MyDrive/BTJ Academy/Data/harga_rumah_cleaned.csv', index=False)